### ISSUE TITLE
Issue tracker for documentation and templates.

### ISSUE THREAD

**Issue by dschaper** [pi-hole/pi-hole#1894]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

Meta-issue for tracking changes and updates to the GitHub templates. Edit as things are changed with link to PR # for completion of line item.

- [x] Remove Signoff checkbox, there's a bot to enforce. Link to DCO wiki in instructions. #1895
- [x] PR template shouldn't include Issues text at the bottom. #1920
- [x] Remove codeblock text place holders. #1920
- [ ] Add "How have you tested this?" to PR template.
